# Generated by Django 5.1.6 on 2025-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=50)),
                ('machine_number', models.IntegerField()),
                ('machine_level', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
            ],
        ),
    ]
